language: python

sudo: false

# Add package
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
    packages:
      - cmake
      - g++-5

compiler:
  - gcc

python:
  - 3.5

cache:
  - pip
  - apt

# List of subdir
env:
  - LANG_DIR=cpp
  - LANG_DIR=python

install:
  - pip3 install -r requirement.txt
  
script:
  - cd $LANG_DIR/build
  - ./build
  - ./test