language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
    packages:
      - cmake
      - gcc-5
      - g++-5
      
compiler:
  - gcc
  - clang

before_script:
  - export CXX=g++-5
  - cd cpp/build
  - cmake ..

script:
  - make

