language: cpp

sudo: false

# Add package
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
    packages:
      - cmake
      - g++-5

compiler:
  - gcc

python:
  - 3.5

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
  - if [ "$CXX" = "clang++"]; then export CXX="clang++-3.5"; fi

# List of subdir
env:
  - LANG_DIR=cpp
  - LANG_DIR=python

install:
  - pip install -r requirement.txt
  
script:
  - cd $LANG_DIR/build
  - ./build
  - ./test